---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: quarkus-template-backend
  title: Quarkus Backend Application
  description: creates the quarkus -workshop
  tags:
    - java
    - quarkus
    - maven
    - workshop
spec:
  owner: mad-workshop-authors
  type: service
  parameters:
    - title: Provide information about the GitHub location
      required:
        - githubOrg
      properties:
        githubOrg:
          title: GitHub Organization
          type: string
          default: devhub-mad
        description:
          title: Description
          type: string
          description: Help others understand what this component is for
    - title: Provide information about the new component
      required:
        - cluster_id
        - namespace
        - owner
      properties:
        cluster_id:
          title: Cluster Id
          type: string
          description: Id of the cluster
          default: .apps.cluster-xxx.sandboxxx.opentlc.com
        namespace:
          title: Namespace
          type: string
          description: Namespace
          default: devhub2
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - [User]
    - title: Provide information about the CI method
      required:
        - ci
      properties:
        ci:
          title: Select a CI method
          type: string
          description: This action will create a CI pipeline for your application based on
            chosen method
          default:  ../../scaffolder-skeleton/cicd/
          enum:
            -  ../../scaffolder-skeleton/cicd/
          enumNames:
            - Tekton
      dependencies:
        ci:
          oneOf:
            - properties:
                ci:
                  const: ../../scaffolder-skeleton/cicd/
            - required:
                - imageRepository
                - imageTag
                - namespace
              properties:
                ci:
                  const:  ../../scaffolder-skeleton/cicd/
                imageRepository:
                  title: Select a registry
                  type: string
                  default: Internal OpenShift Registry
                  enum:
                    - quay.io
                    - image-registry.openshift-image-registry.svc:5000
                  enumNames:
                    - Quay
                    - Internal OpenShift Registry
                  image_tag:
                    title: Image Tag
                    default: latest
                    type: string
                    description: Image tag to use for storing in the internal registry
  steps:
    - id: templateSource
      name: Generating the source code component
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./source
        values:
          githubOrg: ${{parameters.githubOrg}}
          repoName: ${{parameters.namespace}}-backend
          owner: ${{parameters.owner}}
          cluster_id: ${{parameters.cluster_id}}
          namespace: ${{parameters.namespace}}
          component_id: ${{parameters.namespace}}

    - id: templatePipelines
      name: Generating the deployment resources and artefacts
      action: fetch:template
      input:
        url: ./manifests
        copyWithoutTemplating: []
        values:
          component_id: ${{parameters.namespace}}-orders-backend
          description: ${{parameters.description}}
          destination: https://github.com/${{parameters.githubOrg}}/${{parameters.namespace}}-backend-gitops
          source_repository: https://github.com/${{parameters.githubOrg}}/${{parameters.namespace}}-backend
          repository_name: ${{parameters.namespace}}-backend
          git_owner: ${{parameters.githubOrg}}
          cluster: ${{parameters.cluster_id}}
          namespace: ${{parameters.namespace}}
          image_host: ${{parameters.image_host}}
          image_name: ${{parameters.namespace}}/orders-backend
          image_tag: ${{parameters.image_tag}}
        targetPath: ./tenant-gitops

    - id: catalogTemplate
      name: Generating the Catalog Info Component
      action: fetch:template
      input:
        url: ../../scaffolder-skeletons/catalog-info-skeleton/
        values:
          orgName: ${{ parameters.orgName }}
          repoName: ${{ parameters.repoName }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: service
          description: ${{ parameters.description }}
          namespace: ${{ parameters.namespace }}
          imageUrl: ${{ parameters.imageUrl }}
          imageBuilder: s2i-java
          imageRepository: ${{ parameters.imageRepository }}
          port: ${{ parameters.port }}
          ci: ${{ parameters.ci }}
          sourceControl: github.com

    - id: publishSource
      name: Publishing to Source Code Repository
      action: publish:github
      input:
        sourcePath: ./source
        allowedHosts:
          - github.com
        description: ${{parameters.description}}
        repoUrl: github.com?owner=${{parameters.githubOrg}}&repo=${{parameters.namespace}}-backend
        defaultBranch: implementation
        protectDefaultBranch: false
        repoVisibility: public

    - id: publishGitops
      name: Publishing to Deployment Resource Repository
      action: publish:github
      input:
        repoUrl: github.com?owner=${{parameters.githubOrg}}&repo=${{parameters.namespace}}-backend-gitops
        title: gitops resources for ${{parameters.namespace}}-backend
        description: gitops resources for ${{parameters.namespace}}-backend
        sourcePath: ./tenant-gitops
        defaultBranch: implementation
        protectDefaultBranch: false
        repoVisibility: public
    
     - id: createArgoResources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: ${{parameters.namespace}}-backend-bootstrap
        argoInstance: main
        namespace: janus-argocd
        repoUrl: https://github.com/${{parameters.githubOrg}}/${{parameters.namespace}}-backend-gitops.git
        path: 'argocd/'

    - id: registerSource
      name: Registering the Source Code Component
      action: catalog:register
      input:
        repoContentsUrl: ${{steps.publishSource.output.repoContentsUrl}}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Open the Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open the Catalog Info Component
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}