apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: software-templates
  description: A collection of Backstage templates for Janus-IDP
spec:
  type: url
  targets:
   - https://github.com/devhub-mad/modern-app-dev-devhub/blob/implementation/dev-hub-templates/orders-app/template.yaml
    