---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: {{ .Values.demoNamespace }}
spec:
  sso:
    dex:
      openShiftOAuth: true
    provider: dex
  notifications:
    enabled: true
  rbac:
    policy: |
      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin
      g, {{ .Values.namespacePermissions.user }}, role:admin      
    scopes: '[name,groups]'
  server:
    route:
      enabled: true
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: reencrypt
